{
 
   "id": "9f2aa68e-4ded-4a1b-9e03-ba10945f8dba",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "\n",
    "# -----------------------------\n",
    "# BASIC APP CONFIG\n",
    "# -----------------------------\n",
    "st.set_page_config(\n",
    "    page_title=\"Neurodiversity Communication Toolkit (Japan)\",\n",
    "    layout=\"centered\"\n",
    ")\n",
    "\n",
    "# -----------------------------\n",
    "# GLOBAL STYLE (CALM, LOW LOAD)\n",
    "# -----------------------------\n",
    "st.markdown(\"\"\"\n",
    "<style>\n",
    "    body {\n",
    "        background-color: #FAFAFA;\n",
    "    }\n",
    "    .block-container {\n",
    "        padding-top: 2rem;\n",
    "        max-width: 720px;\n",
    "    }\n",
    "    h1, h2, h3 {\n",
    "        font-weight: 600;\n",
    "    }\n",
    "    .card {\n",
    "        background-color: #FFFFFF;\n",
    "        padding: 1.2rem;\n",
    "        border-radius: 16px;\n",
    "        box-shadow: 0px 2px 6px rgba(0,0,0,0.05);\n",
    "        margin-bottom: 1rem;\n",
    "    }\n",
    "</style>\n",
    "\"\"\", unsafe_allow_html=True)\n",
    "\n",
    "# -----------------------------\n",
    "# LANGUAGE TOGGLE\n",
    "# -----------------------------\n",
    "language = st.sidebar.radio(\n",
    "    \"Language / 言語\",\n",
    "    [\"日本語\", \"English\"],\n",
    "    index=0\n",
    ")\n",
    "\n",
    "# -----------------------------\n",
    "# CONTENT DATA (EDIT HERE)\n",
    "# -----------------------------\n",
    "\n",
    "PHRASES = {\n",
    "    \"parents_first\": {\n",
    "        \"title_jp\": \"保護者と初めて話すとき\",\n",
    "        \"title_en\": \"First conversation with parents\",\n",
    "        \"items\": [\n",
    "            {\n",
    "                \"jp\": \"〇〇さんは、とても集中力が高く、興味のあることには深く取り組める力があります。\",\n",
    "                \"en\": \"Your child shows strong focus and can engage deeply with areas of interest.\"\n",
    "            },\n",
    "            {\n",
    "                \"jp\": \"学校では、その力を活かしながら、より安心して学べる方法を一緒に考えたいと思っています。\",\n",
    "                \"en\": \"At school, we would like to think together about ways to support learning comfortably.\"\n",
    "            }\n",
    "        ]\n",
    "    },\n",
    "    \"students\": {\n",
    "        \"title_jp\": \"生徒に説明するとき\",\n",
    "        \"title_en\": \"Explaining to students\",\n",
    "        \"items\": [\n",
    "            {\n",
    "                \"jp\": \"人それぞれ、考え方や感じ方の道は少しずつ違います。\",\n",
    "                \"en\": \"Everyone has slightly different ways of thinking and feeling.\"\n",
    "            }\n",
    "        ]\n",
    "    }\n",
    "}\n",
    "\n",
    "VISUAL_NARRATIVES = {\n",
    "    \"dots\": {\n",
    "        \"title_jp\": \"ドットの物語\",\n",
    "        \"text_jp\": \"人の考えは、点の集まりのようなものです。点の並び方が違うと、見える形も変わります。\",\n",
    "        \"text_en\": \"Thoughts are like dots. When arranged differently, they form different patterns.\"\n",
    "    },\n",
    "    \"waves\": {\n",
    "        \"title_jp\": \"波の物語\",\n",
    "        \"text_jp\": \"集中や疲れには波があります。波を理解すると、無理をしない選択ができます。\",\n",
    "        \"text_en\": \"Focus and energy come in waves. Understanding them helps us choose gently.\"\n",
    "    },\n",
    "    \"paths\": {\n",
    "        \"title_jp\": \"道の物語\",\n",
    "        \"text_jp\": \"学びへの道は一つではありません。それぞれに合った道があります。\",\n",
    "        \"text_en\": \"There is more than one path to learning.\"\n",
    "    }\n",
    "}\n",
    "\n",
    "SCENARIOS = [\n",
    "    {\n",
    "        \"title_jp\": \"保護者に気になる点を伝えたい\",\n",
    "        \"keep_in_mind\": \"関係性を優先し、断定を避ける\",\n",
    "        \"phrases\": \"強みから話し始め、協力をお願いする形にする\",\n",
    "        \"visual\": \"ドットの物語\"\n",
    "    },\n",
    "    {\n",
    "        \"title_jp\": \"教室での配慮を説明したい\",\n",
    "        \"keep_in_mind\": \"子どもの安心感を大切にする\",\n",
    "        \"phrases\": \"選択肢として伝える\",\n",
    "        \"visual\": \"道の物語\"\n",
    "    }\n",
    "]\n",
    "\n",
    "# -----------------------------\n",
    "# NAVIGATION\n",
    "# -----------------------------\n",
    "menu = st.sidebar.radio(\n",
    "    \"Menu\",\n",
    "    [\n",
    "        \"Home / Today\",\n",
    "        \"Phrases & Scripts\",\n",
    "        \"Visual & Narrative Tools\",\n",
    "        \"Guides for Situations\",\n",
    "        \"About the Framework\"\n",
    "    ]\n",
    ")\n",
    "\n",
    "# -----------------------------\n",
    "# HOME\n",
    "# -----------------------------\n",
    "if menu == \"Home / Today\":\n",
    "    st.title(\"Neurodiversity Communication Toolkit\")\n",
    "\n",
    "    st.markdown(\n",
    "        \"<div class='card'>\"\n",
    "        \"日本の教育現場で、やさしく、安心して\"\n",
    "        \"<br>神経多様性について話すための支援ツール\"\n",
    "        \"</div>\",\n",
    "        unsafe_allow_html=True\n",
    "    )\n",
    "\n",
    "    col1, col2, col3 = st.columns(3)\n",
    "    col1.button(\"保護者と話す\")\n",
    "    col2.button(\"生徒と話す\")\n",
    "    col3.button(\"同僚と話す\")\n",
    "\n",
    "    st.markdown(\n",
    "        \"<div class='card'>\"\n",
    "        \"Today’s tip: 言葉を選ぶことは、関係を守ることです。\"\n",
    "        \"</div>\",\n",
    "        unsafe_allow_html=True\n",
    "    )\n",
    "\n",
    "# -----------------------------\n",
    "# PHRASES\n",
    "# -----------------------------\n",
    "elif menu == \"Phrases & Scripts\":\n",
    "    st.title(\"Phrases & Scripts\")\n",
    "\n",
    "    for key, section in PHRASES.items():\n",
    "        st.subheader(section[\"title_jp\"])\n",
    "\n",
    "        for item in section[\"items\"]:\n",
    "            st.markdown(\n",
    "                f\"<div class='card'>{item['jp']}\"\n",
    "                f\"<br><small>{item['en']}</small></div>\",\n",
    "                unsafe_allow_html=True\n",
    "            )\n",
    "\n",
    "# -----------------------------\n",
    "# VISUAL TOOLS\n",
    "# -----------------------------\n",
    "elif menu == \"Visual & Narrative Tools\":\n",
    "    st.title(\"Visual & Narrative Tools\")\n",
    "\n",
    "    for key, item in VISUAL_NARRATIVES.items():\n",
    "        st.subheader(item[\"title_jp\"])\n",
    "        st.markdown(\n",
    "            f\"<div class='card'>{item['text_jp']}\"\n",
    "            f\"<br><small>{item['text_en']}</small></div>\",\n",
    "            unsafe_allow_html=True\n",
    "        )\n",
    "\n",
    "# -----------------------------\n",
    "# SCENARIOS\n",
    "# -----------------------------\n",
    "elif menu == \"Guides for Situations\":\n",
    "    st.title(\"Guides for Situations\")\n",
    "\n",
    "    for s in SCENARIOS:\n",
    "        st.markdown(\n",
    "            f\"<div class='card'>\"\n",
    "            f\"<strong>{s['title_jp']}</strong><br>\"\n",
    "            f\"大切にすること: {s['keep_in_mind']}<br>\"\n",
    "            f\"言葉の方向性: {s['phrases']}<br>\"\n",
    "            f\"おすすめの比喩: {s['visual']}\"\n",
    "            f\"</div>\",\n",
    "            unsafe_allow_html=True\n",
    "        )\n",
    "\n",
    "# -----------------------------\n",
    "# ABOUT\n",
    "# -----------------------------\n",
    "elif menu == \"About the Framework\":\n",
    "    st.title(\"About the Framework\")\n",
    "\n",
    "    st.markdown(\n",
    "        \"<div class='card'>\"\n",
    "        \"このツールは、診断や医療目的のものではありません。\"\n",
    "        \"<br>日本の文化や教育現場に配慮した\"\n",
    "        \"<br>コミュニケーション支援のためのものです。\"\n",
    "        \"</div>\",\n",
    "        unsafe_allow_html=True\n",
    "    )\n",
    "\n",
    "    st.markdown(\"\"\"\n",
    "    **Three Layers**\n",
    "    - Language Layer: 言葉のトーンと選び方\n",
    "    - Visual Layer: ドット・波・道の比喩\n",
    "    - Interaction Layer: 会話の流れ\n",
    "    \"\"\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
